config/routes.rb
Rails.application.routes.draw do
  get "welcome/index"
  root "welcome#index"
  devise_for :users
  resources :scores
  resources :courses, only: [ :index, :show ]
  resources :faculties, only: [ :show ]
  resources :students do
    collection do
      get 'search'
      get 'result'
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/course.rb
class Course < ApplicationRecord
  has_many :scores
  has_many :students, through: :scores
end

app/models/faculty.rb
class Faculty < ApplicationRecord
  has_many :students
end

app/models/score.rb
class Score < ApplicationRecord
  belongs_to :student
  belongs_to :course
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :faculty
  has_one_attached :photo
  has_many :scores
  has_many :courses, through: :scores
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
  before_action :authenticate_user!
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
    @courses = Course.all
  end

  def show
    @course = Course.find(params[:id])
  end
end

app/controllers/faculties_controller.rb
class FacultiesController < ApplicationController
  def show
    @faculty = Faculty.find(params[:id])
    @students = @faculty.students
  end
end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController
  before_action :set_score, only: %i[ show edit update destroy ]

  # GET /scores or /scores.json
  def index
    @scores = Score.all
  end

  # GET /scores/1 or /scores/1.json
  def show
  end

  # GET /scores/new
  def new
    @score = Score.new
  end

  # GET /scores/1/edit
  def edit
  end

  # POST /scores or /scores.json
  def create
    @score = Score.new(score_params)

    respond_to do |format|
      if @score.save
        format.html { redirect_to @score, notice: "Score was successfully created." }
        format.json { render :show, status: :created, location: @score }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @score.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scores/1 or /scores/1.json
  def update
    respond_to do |format|
      if @score.update(score_params)
        format.html { redirect_to @score, notice: "Score was successfully updated." }
        format.json { render :show, status: :ok, location: @score }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @score.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scores/1 or /scores/1.json
  def destroy
    @score.destroy!

    respond_to do |format|
      format.html { redirect_to scores_path, status: :see_other, notice: "Score was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_score
      @score = Score.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def score_params
      params.require(:score).permit(:student_id, :course_id, :score)
    end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: %i[ show edit update destroy ]

  # GET /students or /students.json
  def index
    @students = Student.all
  end

  # GET /students/1 or /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students or /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: "Student was successfully created." }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1 or /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: "Student was successfully updated." }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1 or /students/1.json
  def destroy
    @student.destroy!

    respond_to do |format|
      format.html { redirect_to students_path, status: :see_other, notice: "Student was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  # GET /students/search
  def search
  end

  # GET /students/result
  def result
    @students = Student.joins(:scores).where('course_id = ? AND score = ?', params[:course], params[:score])
    render :index
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def student_params
      params.require(:student).permit(:name, :faculty_id, :grade, :photo)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/faculties_helper.rb
module FacultiesHelper
end

app/helpers/scores_helper.rb
module ScoresHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/courses/index.html.erb
<h1>Courses#index</h1>

<table>
  <% @courses.each do |course| %>
    <tr>
      <td><%= course.name %></td>
      <td><%= link_to '詳細', course_path(course) %></td>
    </tr>
  <% end %>
</table>

app/views/courses/show.html.erb
<h1>Courses#show</h1>

<p>
  <strong>科目名：</strong>
  <%= @course.name %>
</p>

<p>
  <strong>単位数：</strong>
  <%= @course.credit %>
</p>

<p>
  <% if @course.compulsory %>
    <strong>必修科目</strong>
  <% else %>
    <strong>選択科目</strong>
  <% end %>
</p>

<%= link_to 'Back', courses_path %>

app/views/faculties/show.html.erb
<h1>Faculties#show</h1>
<p><b><%= @faculty.name %></b></p>

<table>
  <% @students.each do |student| %>
    <tr>
      <td><%= student.id %></td>
      <td><%= student.name %></td>
    </tr>
  <% end %>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "School" %></title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
    <br><%= image_tag "http://www.sfc.keio.ac.jp/img/logo.png", width: 300 %>
  </body>
</html>

app/views/scores/_form.html.erb
<%= form_with(model: score) do |form| %>
  <% if score.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(score.errors.count, "error") %> prohibited this score from being saved:</h2>

      <ul>
        <% score.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :student_id, style: "display: block" %>
    <%= form.number_field :student_id %>
  </div>

  <div>
    <%= form.label :course_id, style: "display: block" %>
    <%= form.number_field :course_id %>
  </div>

  <div>
    <%= form.label :score, style: "display: block" %>
    <%= form.text_field :score %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/scores/_score.html.erb
<div id="<%= dom_id score %>">
  <p>
    <strong>Student:</strong>
    <%= score.student_id %>
  </p>

  <p>
    <strong>Course:</strong>
    <%= score.course_id %>
  </p>

  <p>
    <strong>Score:</strong>
    <%= score.score %>
  </p>

</div>

app/views/scores/edit.html.erb
<% content_for :title, "Editing score" %>

<h1>Editing score</h1>

<%= render "form", score: @score %>

<br>

<div>
  <%= link_to "Show this score", @score %> |
  <%= link_to "Back to scores", scores_path %>
</div>

app/views/scores/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Scores" %>

<h1>Scores</h1>

<div id="scores">
  <% @scores.each do |score| %>
    <%= render score %>
    <p>
      <%= link_to "Show this score", score %>
    </p>
  <% end %>
</div>

<%= link_to "New score", new_score_path %>

app/views/scores/new.html.erb
<% content_for :title, "New score" %>

<h1>New score</h1>

<%= render "form", score: @score %>

<br>

<div>
  <%= link_to "Back to scores", scores_path %>
</div>

app/views/scores/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @score %>

<div>
  <%= link_to "Edit this score", edit_score_path(@score) %> |
  <%= link_to "Back to scores", scores_path %>

  <%= button_to "Destroy this score", @score, method: :delete %>
</div>

app/views/students/_form.html.erb
<%= form_with(model: student) do |form| %>
  <% if student.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
        <% student.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :faculty_id, style: "display: block" %>
    <%= form.collection_select :faculty_id, Faculty.all, :id, :name %>
  </div>

  <div>
    <%= form.label :grade, style: "display: block" %>
    <% for i in 1..4 %>
      <%= form.radio_button :grade, i %>
      <%= form.label :grade, "#{i}年", value: i %>
    <% end %>
  </div>

  <div class="field">
    <%= form.label :photo %>
    <%= form.file_field :photo %>
  </div>
  
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/students/_student.html.erb
<div id="<%= dom_id student %>">
  <p>
    <strong>Name:</strong>
    <%= student.name %>
  </p>

  <p>
    <strong>Faculty:</strong>
    <%= student.faculty.name %>
  </p>

  <p>
    <strong>Grade:</strong>
    <%= student.grade %>
  </p>

  <p>
    <% if student.photo.attached? %>
      <%= image_tag url_for(student.photo), height: 100 %>
    <% else %>
      No Image
    <% end %>
  </p>

</div>

app/views/students/edit.html.erb
<% content_for :title, "Editing student" %>

<h1>Editing student</h1>

<%= render "form", student: @student %>

<br>

<div>
  <%= link_to "Show this student", @student %> |
  <%= link_to "Back to students", students_path %>
</div>

app/views/students/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Students" %>

<h1>Students</h1>

<div id="students">
  <% @students.each do |student| %>
    <%= render student %>
    <p>
      <%= link_to "Show this student", student %>
    </p>
  <% end %>
</div>

<%= link_to "New student", new_student_path %>

app/views/students/new.html.erb
<% content_for :title, "New student" %>

<h1>New student</h1>

<%= render "form", student: @student %>

<br>

<div>
  <%= link_to "Back to students", students_path %>
</div>

app/views/students/search.html.erb
<h1>成績を指定して学生を検索</h1>

<%= form_with(url: result_students_path, method: :get) do |form| %>

  <div>
    <%= form.label :course, '科目' %>
    <%= form.collection_select :course, Course.all, :id, :name %>
  </div>

  <div>
    <%= form.label :score, '成績' %>
    <%= form.select :score, {'S' => 'S', 'A' => 'A', 'B' => 'B', 'C' => 'C', 'D' => 'D'} %>
  </div>

  <div>
    <%= form.submit '検索' %>
  </div>

<% end %>

app/views/students/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @student %>

<div>
  <%= link_to "Edit this student", edit_student_path(@student) %> |
  <%= link_to "Back to students", students_path %>

  <%= button_to "Destroy this student", @student, method: :delete %>
</div>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>

<% if user_signed_in? %>
  <p>You are <%= current_user.email %></p>
  <%= button_to 'Logout', destroy_user_session_path, method: :delete %>
<% else %>
  <%= button_to 'Login', new_user_session_path %>
<% end %>